/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kerkesaperleje;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Iliriani
 */
public class Administrimi extends javax.swing.JFrame {
        private LidhjaMeDb lidhja;
        private int id=0;
        private boolean insert;
    /**
     * Creates new form Administrimi
     */
    public Administrimi() {
        initComponents();
        mbusheKombon();
    }

    
    
    
    
    public void mbusheKombon(){
     try{
         lidhja=new LidhjaMeDb();
        ResultSet rs=lidhja.merrirolet();
        while(rs.next()){
           kmbrolet.addItem(rs.getString("roli")); 
        }
     }
     catch(Exception e){e.printStackTrace();}
    }
    
    
    
    //mbushet tabela me te dhena te filtruara nga DB
    public void mbushetabelen(){
         try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection conn = DriverManager.getConnection("jdbc:odbc:lidhja_sql");
            Statement stmt = conn.createStatement();
            String sql = "select p.idperdoruesi,p.emri AS Emri,p.mbiemri AS Mbiemri,r.roli AS Roli"
                            +" from perdoruesit p "
                            +" inner join rolet r " 
                            +" on p.idroli=r.idroli "
                            +"WHERE roli='"+(String)kmbrolet.getSelectedItem()+"'"
                            +"AND emri like'%"+txtpunonjesi.getText()+"%'";

            //System.out.println(sql);
            ResultSet rs = stmt.executeQuery(sql);
            tblrolet.setModel(DBUtils.resultSetToTableModel(rs));
            tblrolet.getColumn("idperdoruesi").setWidth(0);
            tblrolet.getColumn("idperdoruesi").setMinWidth(0);
            tblrolet.getColumn("idperdoruesi").setMaxWidth(0);
          
        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladministrimi = new javax.swing.JLabel();
        btniri = new javax.swing.JButton();
        btnndrysho = new javax.swing.JButton();
        lblroli = new javax.swing.JLabel();
        kmbrolet = new javax.swing.JComboBox();
        txtpunonjesi = new javax.swing.JTextField();
        lblpunonjesi = new javax.swing.JLabel();
        btnkerko = new javax.swing.JButton();
        btnfshije = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrolet = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbladministrimi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbladministrimi.setForeground(new java.awt.Color(153, 153, 0));
        lbladministrimi.setText("Administrimi");

        btniri.setText("I ri");
        btniri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniriActionPerformed(evt);
            }
        });

        btnndrysho.setText("Ndrysho");
        btnndrysho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnndryshoActionPerformed(evt);
            }
        });

        lblroli.setText("Roli:");

        kmbrolet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Zgjidh>" }));

        lblpunonjesi.setText("Punonjesi:");

        btnkerko.setText("Kerko");
        btnkerko.setToolTipText("");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        btnfshije.setText("Fshije");
        btnfshije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfshijeActionPerformed(evt);
            }
        });

        tblrolet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Emri", "Mbiemri","Roli"
            }
        ));
        tblrolet.getTableHeader().setReorderingAllowed(false);
        tblrolet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblroletMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrolet);

        jMenu1.setText("Kerkesat");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Raportet");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administrimi");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladministrimi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btniri)
                            .addGap(18, 18, 18)
                            .addComponent(btnndrysho)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnfshije))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblroli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kmbrolet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(lblpunonjesi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtpunonjesi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnkerko)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbladministrimi)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btniri)
                    .addComponent(btnndrysho)
                    .addComponent(btnfshije))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblroli)
                    .addComponent(kmbrolet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpunonjesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpunonjesi)
                    .addComponent(btnkerko))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblroletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblroletMouseClicked
                        int row = tblrolet.getSelectedRow();
                        id=(int)tblrolet.getModel().getValueAt(row, 0);
                        System.out.println(id);
    }//GEN-LAST:event_tblroletMouseClicked

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
         if(kmbrolet.getSelectedIndex()==0)
         {JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje role te caktuar!");
         }
         else{
            mbushetabelen();
            tblrolet.setVisible(true);
         }
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void btnfshijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfshijeActionPerformed
                 try{ 
           //int reply = JOptionPane.showConfirmDialog(this, "a deshironi ta fshini kerkesen?", "fshije", JOptionPane.YES_NO_OPTION);
             if(tblrolet.isVisible() && id!=0)
             {Object[] options = {"Po",
                    "Jo"};
                   int zgjedhja= JOptionPane.showOptionDialog(this, "A deshironi ta fshini punonjesin e zgjedhur?","Konfirmo", 
                   JOptionPane.YES_NO_OPTION, 
                   JOptionPane.WARNING_MESSAGE, 
                   null, options, options[1]);

            if (zgjedhja == JOptionPane.YES_OPTION)
            { 
                LidhjaMeDb lidhja=new LidhjaMeDb();
                int n=lidhja.fshijepunonjesin(id);
                mbushetabelen();
                }
  
            }
             else{JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje punonjes!");}
      }
          catch(Exception e){System.out.println("gabim te butoni fshije");
                }
    }//GEN-LAST:event_btnfshijeActionPerformed

    private void btniriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniriActionPerformed
        Administro a=new Administro(insert,0,"");
        a.setVisible(true);
    }//GEN-LAST:event_btniriActionPerformed

    private void btnndryshoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnndryshoActionPerformed
        if(id==0)
        {JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje person!");
        }
        else{
        Administro k=new Administro(false, id,"");
        k.setVisible(true);
        System.out.println(id);
        }
    }//GEN-LAST:event_btnndryshoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Administrimi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfshije;
    private javax.swing.JButton btniri;
    private javax.swing.JButton btnkerko;
    private javax.swing.JButton btnndrysho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kmbrolet;
    private javax.swing.JLabel lbladministrimi;
    private javax.swing.JLabel lblpunonjesi;
    private javax.swing.JLabel lblroli;
    private javax.swing.JTable tblrolet;
    private javax.swing.JTextField txtpunonjesi;
    // End of variables declaration//GEN-END:variables
}
