/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kerkesaperleje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Iliriani
 */
public class Administro extends javax.swing.JFrame {

    private LidhjaMeDb lidhja;
    private boolean insert;
    private int id;
    private int idroli;
    private String roli;

    /**
     * Creates new form Administro
     */
    public Administro(boolean gjendja, int id, String roli) {

        this.insert = gjendja;
        this.id = id;
        this.roli = roli;

        initComponents();
        mbusheKombon();
        kontrollogjendjen();
    }

//e mbush kombon kmbrolet me te dhena nga DB 
    public void mbusheKombon() {
        try {
            lidhja = new LidhjaMeDb();
            ResultSet rs = lidhja.merrirolet();
            while (rs.next()) {
                kmbrolet.addItem(rs.getString("roli"));
            }
            
            LidhjaMeDb.mbyllelidhjen();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//Kontrollon se a jemi duke e futur nje kerkese te re apo duke e ndryshuar ate
    public boolean kontrollogjendjen() {
        try {
            if (insert == true) {
                //Nese kemi hyre per te insertuar
                System.out.println("insert");
                return true;
            } else {
                //Kur te bejmi ndonje update te kerkesave
                System.out.println("update " + id);
                mbushitxt(id);
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return insert;

    }

//metoda e cila kthen vleren e indexit ne kombo kur jemi ne update
    public int kthe_vleren_kombos(int v) throws Exception {


        int i = 1;
        int vlera = 1;
        Statement stmt = LidhjaMeDb.hapelidhjen();
        //CallableStatement stmt = conn.prepareCall("{call procedura1(?)}");
        //stmt.setInt(1, 1);
        //ResultSet rs=stmt.executeQuery();
        String sql = "select idroli from rolet";
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            if (rs.getInt("idroli") == v) {
                vlera = i;
            } else {
                i++;
            }
        }
        LidhjaMeDb.mbyllelidhjen();
        return vlera;

    }

//Metoda qe i mbushe fushat perkates kur kemi te bejme me update
    public void mbushitxt(int id) {

        System.out.println("Hyrja ne mbushitxt " + id);
        try {
            lidhja = new LidhjaMeDb();
            ResultSet rs = lidhja.vlerat_perdoruesit(id);
            while (rs.next()) {
                System.out.println("Hyrja rs.next");
                //kmbrolet.setSelectedIndex(rs.getInt("idroli"));
                kmbrolet.setSelectedIndex(kthe_vleren_kombos(rs.getInt("idroli")));
                txtperdoruesi.setText(rs.getString("perdoruesi"));
                //txtfjalekalimi.setText(rs.getString("fjalekalimi"));
                //txtkonfirmo.setText(rs.getString("fjalekalimi"));
                txtemri.setText(rs.getString("emri"));
                txtmbiemri.setText(rs.getString("mbiemri"));
                System.out.println("Mbarimi rs.next ne mbushitxt");
            }
            LidhjaMeDb.mbyllelidhjen();

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("gabim te metoda mbushitxt");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladministro = new javax.swing.JLabel();
        lblemri = new javax.swing.JLabel();
        lblmbiemri = new javax.swing.JLabel();
        lblfjalekalimi = new javax.swing.JLabel();
        lblkonfirmo = new javax.swing.JLabel();
        lblroli = new javax.swing.JLabel();
        txtemri = new javax.swing.JTextField();
        txtmbiemri = new javax.swing.JTextField();
        kmbrolet = new javax.swing.JComboBox();
        btnruaj = new javax.swing.JButton();
        bntanulo = new javax.swing.JButton();
        txtfjalekalimi = new javax.swing.JPasswordField();
        txtkonfirmo = new javax.swing.JPasswordField();
        lblperdoruesi = new javax.swing.JLabel();
        txtperdoruesi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        lbladministro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbladministro.setForeground(new java.awt.Color(153, 153, 0));
        lbladministro.setText("Administrimi");

        lblemri.setText("Emri:");

        lblmbiemri.setText("Mbiemri:");

        lblfjalekalimi.setText("Fjalekalimi:");

        lblkonfirmo.setText("Konfirmo Fjalekalimin:");

        lblroli.setText("Roli:");

        kmbrolet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Zgjidh>" }));
        kmbrolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmbroletActionPerformed(evt);
            }
        });

        btnruaj.setText("Ruaj");
        btnruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruajActionPerformed(evt);
            }
        });

        bntanulo.setText("Anulo");
        bntanulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntanuloActionPerformed(evt);
            }
        });

        lblperdoruesi.setText("Perdoruesi:");

        jMenu1.setText("Kerkesat");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Raportet");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administrimi");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnruaj)
                        .addGap(26, 26, 26)
                        .addComponent(bntanulo)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladministro)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblkonfirmo)
                                            .addComponent(lblfjalekalimi)
                                            .addComponent(lblperdoruesi)
                                            .addComponent(lblmbiemri)
                                            .addComponent(lblemri))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtemri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(txtfjalekalimi, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtmbiemri, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtkonfirmo, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtperdoruesi, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblroli)
                                        .addGap(18, 18, 18)
                                        .addComponent(kmbrolet, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbladministro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemri, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblmbiemri)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtperdoruesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblperdoruesi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfjalekalimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfjalekalimi))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkonfirmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkonfirmo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kmbrolet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblroli))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnruaj)
                            .addComponent(bntanulo))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnruajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruajActionPerformed
        try {
            if (kmbrolet.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Zgjidheni njerin nga rolet.");
            }
            Enkriptimi e = new Enkriptimi();
            if (insert) {
                if (txtfjalekalimi.getText().equals(txtkonfirmo.getText())) {
                    LidhjaMeDb lidhja = new LidhjaMeDb();
                    int idroli = lidhja.ktheidroli((String) kmbrolet.getSelectedItem());
                    int rs = lidhja.ruajepunonjesin(idroli, txtperdoruesi.getText(), e.enc(txtfjalekalimi.getText()),
                            txtemri.getText(), txtmbiemri.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Fjalekalimet tuaja nuk perputhen!");
                }
            } else if (txtfjalekalimi.getText().equals(txtkonfirmo.getText())) {
                LidhjaMeDb lidhja = new LidhjaMeDb();
                int n = lidhja.updatepunonjesi(id, idroli, txtperdoruesi.getText(), e.enc(txtfjalekalimi.getText()), txtemri.getText(), txtmbiemri.getText());
                System.out.println("update");
            } else {
                JOptionPane.showMessageDialog(this, "Fjalekalimet tuaja nuk perputhen!");
            }


        } catch (Exception e) {
            System.out.println("gabim te ruaj punonjesin!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnruajActionPerformed

    private void bntanuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntanuloActionPerformed
        this.dispose();
    }//GEN-LAST:event_bntanuloActionPerformed

    private void kmbroletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmbroletActionPerformed
        try {
            Statement stmt = LidhjaMeDb.hapelidhjen();
            //CallableStatement stmt = conn.prepareCall("{call procedura1(?)}");
            //stmt.setInt(1, 1);
            //ResultSet rs=stmt.executeQuery();
            String sql = "select idroli from rolet where roli='" + (String) kmbrolet.getSelectedItem() + "'";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                idroli = rs.getInt("idroli");
            }
            LidhjaMeDb.mbyllelidhjen();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_kmbroletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Administro(true, 0, "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntanulo;
    private javax.swing.JButton btnruaj;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JComboBox kmbrolet;
    private javax.swing.JLabel lbladministro;
    private javax.swing.JLabel lblemri;
    private javax.swing.JLabel lblfjalekalimi;
    private javax.swing.JLabel lblkonfirmo;
    private javax.swing.JLabel lblmbiemri;
    private javax.swing.JLabel lblperdoruesi;
    private javax.swing.JLabel lblroli;
    private javax.swing.JTextField txtemri;
    private javax.swing.JPasswordField txtfjalekalimi;
    private javax.swing.JPasswordField txtkonfirmo;
    private javax.swing.JTextField txtmbiemri;
    private javax.swing.JTextField txtperdoruesi;
    // End of variables declaration//GEN-END:variables
}
