/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kerkesaperleje;

import java.sql.*;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;

/**
 *
 * @author Iliriani
 */
public class Kerkesat extends javax.swing.JFrame {
    private LidhjaMeDb lidhja;
    private int id=0;
   // private ResultSet rst;
    /*
     * Creates new form Kerkesat
     */
    public Kerkesat() {
        initComponents();
        tblkerkesat.setVisible(false);
        //jScrollPane3.setVisible(false);
        //mbushet kombo kerko me te dhena statike
        cmbkerko.addItem("Numri i Protokollit");
        cmbkerko.addItem("Kompania");
        cmbkerko.addItem("Lloji i Lejes");
        cmbkerko.addItem("Aktiviteti");
        cmbkerko.addItem("Pergjigjja e Komisionit");
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        btnregjistro = new javax.swing.JButton();
        btnndysho = new javax.swing.JButton();
        cmbkerko = new javax.swing.JComboBox();
        lblkerkote = new javax.swing.JLabel();
        lblkerkoje = new javax.swing.JLabel();
        txtkerkoje = new javax.swing.JTextField();
        btnkerko = new javax.swing.JButton();
        btnpastro = new javax.swing.JButton();
        lblkerkesa = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkerkesat = new javax.swing.JTable();
        lblporosia = new javax.swing.JLabel();
        btnfshije = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        btnregjistro.setText("Regjistro");
        btnregjistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregjistroActionPerformed(evt);
            }
        });

        btnndysho.setText("Ndrysho");
        btnndysho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnndyshoActionPerformed(evt);
            }
        });

        cmbkerko.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Zgjidh>" }));
        cmbkerko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbkerkoMouseClicked(evt);
            }
        });

        lblkerkote.setText("Kerko te:");

        lblkerkoje.setText("Kerkoje:");

        btnkerko.setText("kerko");
        btnkerko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkerkoActionPerformed(evt);
            }
        });

        btnpastro.setText("Pastro");

        lblkerkesa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblkerkesa.setForeground(new java.awt.Color(102, 102, 0));
        lblkerkesa.setText("Kerkesat");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        tblkerkesat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Zgjedh", "Nr.protokollit", "Kompania", "Ljoj i Lejes","Aktiviteti-Veprimataria","Pergjigjja e komisionit","Ndrysho"
            }
        ));
        tblkerkesat.getTableHeader().setReorderingAllowed(false);
        tblkerkesat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkerkesatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblkerkesat);
        tblkerkesat.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jCheckBox1));

        jScrollPane3.setViewportView(jScrollPane2);

        btnfshije.setText("Fshije");
        btnfshije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfshijeActionPerformed(evt);
            }
        });

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu1.setText("Kerkesat");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Raportet");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Administrimi");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblkerkote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblkerkoje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtkerkoje, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnkerko))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnregjistro)
                                .addGap(27, 27, 27)
                                .addComponent(btnndysho)
                                .addGap(64, 64, 64)
                                .addComponent(btnfshije)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(btnpastro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblkerkesa)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblkerkesa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregjistro)
                    .addComponent(btnndysho)
                    .addComponent(jCheckBox1)
                    .addComponent(btnfshije))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbkerko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkerkote)
                    .addComponent(lblkerkoje)
                    .addComponent(txtkerkoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkerko)
                    .addComponent(btnpastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   /* 
    *nderroet vlera e zgjedhur ne combo me nje vlere
    * ne kontekst te njejte nga DB
    */
      public String merreVlerenEkombos(){
        String cmb=(String)cmbkerko.getSelectedItem();
        String s;
        switch(cmb){
            case "Numri i Protokollit": s="nr_protokollit"; break;
            case "Kompania": s="kompania"; break; 
            case "Lloji i Lejes": s="lloji_Lejes"; break;
            case "Aktiviteti": s="aktiviteti"; break;
            case "Pergjigjja e Komisionit": s="pergjigjja"; break;
            default: s="gabim ne zgjedhjen e vleres ne kombo";    
        
        }
        
        return s;
    }
    
    
//mbushet tabela me te dhena te filtruara nga DB
    public void mbushetabelen(){
         try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection conn = DriverManager.getConnection("jdbc:odbc:lidhja_sql");
            Statement stmt = conn.createStatement();
            String sql = "select k.idkerkesa, k.nr_protokollit as \"Numri i Protokollit\", "
                        +"k.kompania as \"Kompania\", lj.lloji_lejes as \"Lloji i Lejes\", "
                        +"ak.aktiviteti as \"Aktiviteti\", p.pergjigjja as \"Pergjigjja e Komisionit\" " 
                        +"from kerkesat k "
                        +"join llojet_lejes lj on k.idlloji=lj.idlloji "
                        +"join aktivitetet ak on k.idaktiviteti=ak.idaktiviteti "
                        +"join pergjigjjet_komisionit p on k.idpergjigjja=p.idpergjigjja "
                        +"WHERE "+ merreVlerenEkombos() + " LIKE '%"+txtkerkoje.getText()+"%'";

            //System.out.println(sql);
            ResultSet rs = stmt.executeQuery(sql);
            tblkerkesat.setModel(DBUtils.resultSetToTableModel(rs));
            tblkerkesat.getColumn("idkerkesa").setWidth(0);
            tblkerkesat.getColumn("idkerkesa").setMinWidth(0);
            tblkerkesat.getColumn("idkerkesa").setMaxWidth(0);
          
        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    
      //Kthen id-ne e kerkeses se zgjedhur ne tabel 
       public int merreid(){
           return id;
       }
    
    
    
    
    
    
    
    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void btnregjistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregjistroActionPerformed
        RegjistroKerkese rk=new RegjistroKerkese(true, 0,"");
        rk.setVisible(true);
        
    }//GEN-LAST:event_btnregjistroActionPerformed

    private void btnndyshoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnndyshoActionPerformed
        if(id==0)
        {JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje kerkese!");
        }
        else{
        RegjistroKerkese k=new RegjistroKerkese(false, id,"");
        k.setVisible(true);
        System.out.println(this.merreid());
        }
    }//GEN-LAST:event_btnndyshoActionPerformed

    private void tblkerkesatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkerkesatMouseClicked
        int row = tblkerkesat.getSelectedRow();
        id= (int)tblkerkesat.getModel().getValueAt(row, 0);
    }//GEN-LAST:event_tblkerkesatMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnkerkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkerkoActionPerformed
         if(cmbkerko.getSelectedIndex()==0)
         {JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje kerkese!");
         }
         else{
            mbushetabelen();
            tblkerkesat.setVisible(true);
         }
        
        
        //System.out.println(txtkerkoje.getText());
    }//GEN-LAST:event_btnkerkoActionPerformed

    private void cmbkerkoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbkerkoMouseClicked
        // TODO add your handling code here:
        System.out.println((String)cmbkerko.getSelectedItem());
    }//GEN-LAST:event_cmbkerkoMouseClicked

    private void btnfshijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfshijeActionPerformed
      try{ 
           //int reply = JOptionPane.showConfirmDialog(this, "a deshironi ta fshini kerkesen?", "fshije", JOptionPane.YES_NO_OPTION);
             if(tblkerkesat.isVisible() && id!=0)
             {Object[] options = {"Po",
                    "Jo"};
                   int zgjedhja= JOptionPane.showOptionDialog(this, "A deshironi ta fshini kerkesen e zgjedhur?","Konfirmo", 
                   JOptionPane.YES_NO_OPTION, 
                   JOptionPane.WARNING_MESSAGE, 
                   null, options, options[1]);

            if (zgjedhja == JOptionPane.YES_OPTION)
            { 
          lidhja=new LidhjaMeDb();
          int n=lidhja.fshijekerkesen(id);
            mbushetabelen();}
  
            }
             else{JOptionPane.showMessageDialog(this, "Ju lutem zgjidheni nje kerkese!");}
      }
          catch(Exception e){System.out.println("gabim te butoni fshije");
                }
    }//GEN-LAST:event_btnfshijeActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Raportet r=new Raportet("");
        r.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kerkesat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kerkesat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kerkesat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kerkesat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kerkesat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfshije;
    private javax.swing.JButton btnkerko;
    private javax.swing.JButton btnndysho;
    private javax.swing.JButton btnpastro;
    private javax.swing.JButton btnregjistro;
    private javax.swing.JComboBox cmbkerko;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblkerkesa;
    private javax.swing.JLabel lblkerkoje;
    private javax.swing.JLabel lblkerkote;
    private javax.swing.JLabel lblporosia;
    private javax.swing.JTable tblkerkesat;
    private javax.swing.JTextField txtkerkoje;
    // End of variables declaration//GEN-END:variables
}
