package kerkesaperleje;


//import com.lowagie.text.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JButton;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iliriani
 */
public class Kyqja extends javax.swing.JFrame {
 private LidhjaMeDb lidhja;
 private String user;
 private String pass;
 private String roli;
    /**
     * Creates new form Kyqja
     */
    public Kyqja() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\Flamuri_i_Kosoves.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblporosia = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnkycu = new javax.swing.JButton();
        lblperdoruesi = new javax.swing.JLabel();
        txtperdoruesi = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menaxhimi i kerkesave per leje");
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblporosia.setForeground(new java.awt.Color(255, 51, 51));

        jInternalFrame1.setVisible(true);

        jpass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpass.setDoubleBuffered(true);
        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });

        jLabel3.setText("fjalekalimi:");

        btnkycu.setText("Kycu");
        btnkycu.setSelected(true);
        btnkycu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkycuActionPerformed(evt);
            }
        });
        btnkycu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnkycuKeyReleased(evt);
            }
        });

        lblperdoruesi.setText("perdoruesi:");

        txtperdoruesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperdoruesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnkycu)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblperdoruesi)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpass)
                            .addComponent(txtperdoruesi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblperdoruesi)
                    .addComponent(txtperdoruesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnkycu)
                .addContainerGap())
        );

        jMenu1.setText("Kerkesat");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Raportet");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administrimi");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblporosia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(lblporosia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkycuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkycuActionPerformed
//        System.out.println(txtperdoruesi.getText());
       
       try{ 
           Enkriptimi e=new Enkriptimi();
            this.user=txtperdoruesi.getText();
            this.pass=e.enc(jpass.getText());
            //this.pass=jpass.getText();
            int i=0;
            lidhja=new LidhjaMeDb(); 
            ResultSet rs=lidhja.valido(user, pass); 
            while(rs.next()){
                i++;
                //System.out.println(rs.getString("roli"));
                 this.roli=rs.getString("roli");
                Kerkimi k=new Kerkimi("kerkesat","idkerkesa","RegjistroKerkese","Kerkesat",roli);
                k.setVisible(true);
                k.setTitle("Menaxhimi i kerkesave per leje");
                //Image im = (Image)Toolkit.getDefaultToolkit().getImage("C:\\node.jpg");
                 k.setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\Flamuri_i_Kosoves.png"));
            }
        if(i==0){lblporosia.setText("Keni dhene fjalekalim jo te sakte");}
        else{lblporosia.setText("");}
        lidhja.mbyllelidhjen();
        
       }
       catch(Exception e){System.out.println("ka dale nje gabim gjate ekzekutimit");
                          e.printStackTrace();}
    }//GEN-LAST:event_btnkycuActionPerformed

    private void txtperdoruesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperdoruesiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtperdoruesiActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        System.out.println("into");
    }//GEN-LAST:event_formComponentShown

    private void btnkycuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnkycuKeyReleased
        if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER )
            {System.out.println("enter");
            btnkycuActionPerformed(null);
              //this.btnkycu.getAction().actionPerformed(java.awt.event.ActionEvent e);
            }  

    }//GEN-LAST:event_btnkycuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kyqja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kyqja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kyqja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kyqja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kyqja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkycu;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JLabel lblperdoruesi;
    private javax.swing.JLabel lblporosia;
    private java.awt.TextField txtperdoruesi;
    // End of variables declaration//GEN-END:variables
}
